name: CI - TaskFly

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar Dependências
        run: npm install

      - name: Executar Linting (Análise Estática)
        run: npm run lint

      - name: Executar Testes Automatizados
        run: npm test -- --watchAll=false
